module.exports = function (RED) {
    'use strict';

    const { spawn } = require('child_process');
    const fs = require('fs');
    const os = require('os');
    const path = require('path');
    const net = require('net');

    function resolveBinary(userPath) {
        if (userPath && userPath.trim() !== '') {
            return userPath.trim();
        }
        if (process.platform !== 'win32') {
            return 'mosquitto';
        }
        // On Windows the installer does not always add mosquitto to PATH.
        // Check the standard install locations before falling back to the
        // bare name (which relies on PATH).
        const candidates = [];
        if (process.env['ProgramFiles']) {
            candidates.push(path.join(process.env['ProgramFiles'], 'mosquitto', 'mosquitto.exe'));
        }
        if (process.env['ProgramFiles(x86)']) {
            candidates.push(path.join(process.env['ProgramFiles(x86)'], 'mosquitto', 'mosquitto.exe'));
        }
        for (const c of candidates) {
            try {
                if (fs.existsSync(c)) return c;
            } catch (e) { /* ignore */ }
        }
        return 'mosquitto.exe';
    }

    function portInUse(port, host) {
        return new Promise((resolve) => {
            const tester = net.createServer()
                .once('error', (err) => {
                    resolve(err.code === 'EADDRINUSE');
                })
                .once('listening', () => {
                    tester.close(() => resolve(false));
                })
                .listen(port, host || '0.0.0.0');
        });
    }

    function MosquittoBrokerNode(config) {
        RED.nodes.createNode(this, config);
        const node = this;

        const port = parseInt(config.port, 10) || 1883;
        const bind = (config.bind || '').trim();
        const allowAnonymous = config.allowAnonymous !== false;
        const persistence = !!config.persistence;
        const customConfigPath = (config.configPath || '').trim();
        const binaryPath = resolveBinary(config.binaryPath);
        const logToConsole = !!config.logToConsole;

        const username = (node.credentials && node.credentials.username) || '';
        const password = (node.credentials && node.credentials.password) || '';

        const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nr-mosquitto-'));
        const generatedConfig = path.join(workDir, 'mosquitto.conf');
        const pwFile = path.join(workDir, 'passwd');
        const persistenceDir = path.join(workDir, 'data');

        let child = null;
        let stopping = false;
        let restartTimer = null;

        function cleanupWorkDir() {
            try {
                fs.rmSync(workDir, { recursive: true, force: true });
            } catch (e) {
                node.warn('Could not remove temp dir: ' + e.message);
            }
        }

        function writePasswordFile() {
            if (!username || !password) return null;
            // Plain format: mosquitto can read a plain user:password file when
            // `password_file` is combined with `allow_plain_passwords true`.
            // However, that option only exists on some builds. The portable
            // solution is to ask mosquitto_passwd to hash it. If that is not
            // available, fall back to plain format and warn the user.
            const plainContent = `${username}:${password}\n`;
            fs.writeFileSync(pwFile, plainContent, { mode: 0o600 });
            // Try to hash via mosquitto_passwd if available.
            try {
                const hasher = spawn('mosquitto_passwd', ['-U', pwFile]);
                return new Promise((resolve) => {
                    hasher.on('error', () => {
                        node.warn('mosquitto_passwd not found; password file left in plain format.');
                        resolve(pwFile);
                    });
                    hasher.on('exit', (code) => {
                        if (code !== 0) {
                            node.warn('mosquitto_passwd exited with code ' + code + '; password file may be unusable.');
                        }
                        resolve(pwFile);
                    });
                });
            } catch (e) {
                node.warn('Could not hash password file: ' + e.message);
                return pwFile;
            }
        }

        function buildConfig() {
            const lines = [];
            lines.push('# Auto-generated by node-red-contrib-mosquitto-broker');
            if (bind) {
                lines.push(`listener ${port} ${bind}`);
            } else {
                lines.push(`listener ${port}`);
            }
            lines.push(`allow_anonymous ${allowAnonymous ? 'true' : 'false'}`);
            if (username && password) {
                lines.push(`password_file ${pwFile}`);
            }
            if (persistence) {
                fs.mkdirSync(persistenceDir, { recursive: true });
                lines.push('persistence true');
                lines.push(`persistence_location ${persistenceDir}${path.sep}`);
            } else {
                lines.push('persistence false');
            }
            lines.push('log_dest stdout');
            lines.push('log_type error');
            lines.push('log_type warning');
            lines.push('log_type notice');
            return lines.join('\n') + '\n';
        }

        function setStatus(fill, shape, text) {
            node.status({ fill, shape, text });
        }

        async function start() {
            if (child) return;

            try {
                const inUse = await portInUse(port, bind || '0.0.0.0');
                if (inUse) {
                    setStatus('red', 'ring', `port ${port} in use`);
                    node.error(`Port ${port} is already in use`);
                    return;
                }

                let configFileToUse;
                if (customConfigPath) {
                    if (!fs.existsSync(customConfigPath)) {
                        setStatus('red', 'ring', 'config not found');
                        node.error(`Config file not found: ${customConfigPath}`);
                        return;
                    }
                    configFileToUse = customConfigPath;
                } else {
                    if (username && password) {
                        await writePasswordFile();
                    }
                    fs.writeFileSync(generatedConfig, buildConfig(), { mode: 0o600 });
                    configFileToUse = generatedConfig;
                }

                setStatus('yellow', 'ring', 'starting');

                child = spawn(binaryPath, ['-c', configFileToUse], {
                    stdio: ['ignore', 'pipe', 'pipe']
                });

                child.on('error', (err) => {
                    setStatus('red', 'ring', 'spawn error');
                    const hint = err.code === 'ENOENT'
                        ? ' - binary not found. Run "npm run install-mosquitto" in the module directory, or install mosquitto manually.'
                        : '';
                    node.error(`Failed to start mosquitto (${binaryPath}): ${err.message}${hint}`);
                    child = null;
                });

                child.stdout.on('data', (data) => {
                    const text = data.toString().trim();
                    if (logToConsole && text) node.log(text);
                    node.send({ topic: 'mosquitto/stdout', payload: text });
                });

                child.stderr.on('data', (data) => {
                    const text = data.toString().trim();
                    if (logToConsole && text) node.warn(text);
                    node.send({ topic: 'mosquitto/stderr', payload: text });
                });

                child.on('exit', (code, signal) => {
                    const wasRunning = child !== null;
                    child = null;
                    if (stopping) {
                        setStatus('grey', 'ring', 'stopped');
                        return;
                    }
                    const reason = signal ? `signal ${signal}` : `code ${code}`;
                    setStatus('red', 'ring', `exited (${reason})`);
                    node.warn(`mosquitto exited unexpectedly (${reason}); retrying in 5s`);
                    if (wasRunning && !restartTimer) {
                        restartTimer = setTimeout(() => {
                            restartTimer = null;
                            start();
                        }, 5000);
                    }
                });

                // Give the broker a moment to actually bind, then mark running.
                setTimeout(() => {
                    if (child) {
                        setStatus('green', 'dot', `running :${port}`);
                    }
                }, 500);
            } catch (err) {
                setStatus('red', 'ring', 'start failed');
                node.error('Error starting broker: ' + err.message);
            }
        }

        function stop(done) {
            stopping = true;
            if (restartTimer) {
                clearTimeout(restartTimer);
                restartTimer = null;
            }
            if (!child) {
                cleanupWorkDir();
                if (done) done();
                return;
            }
            const proc = child;
            const killTimeout = setTimeout(() => {
                try { proc.kill('SIGKILL'); } catch (e) { /* ignore */ }
            }, 5000);

            proc.once('exit', () => {
                clearTimeout(killTimeout);
                child = null;
                cleanupWorkDir();
                if (done) done();
            });

            try { proc.kill('SIGTERM'); } catch (e) {
                clearTimeout(killTimeout);
                cleanupWorkDir();
                if (done) done();
            }
        }

        node.on('input', (msg, send, doneCb) => {
            const cmd = (msg.payload && typeof msg.payload === 'object')
                ? msg.payload.command
                : msg.payload;
            if (cmd === 'start') {
                start().then(() => doneCb && doneCb());
                return;
            }
            if (cmd === 'stop') {
                stop(() => doneCb && doneCb());
                return;
            }
            if (cmd === 'restart') {
                stop(() => {
                    stopping = false;
                    start().then(() => doneCb && doneCb());
                });
                return;
            }
            if (cmd === 'status') {
                send({ topic: 'mosquitto/status', payload: { running: !!child, port, bind } });
                doneCb && doneCb();
                return;
            }
            doneCb && doneCb();
        });

        node.on('close', (done) => {
            stop(done);
        });

        start();
    }

    RED.nodes.registerType('mosquitto-broker', MosquittoBrokerNode, {
        credentials: {
            username: { type: 'text' },
            password: { type: 'password' }
        }
    });
};
